var searchData=
[
  ['name_0',['name',['../class_domain_1_1_name.html#a06db67a169f3f49e482528babfb8576d',1,'Domain.Name.Name()'],['../class_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_out_1_1_named_model.html#a2be5c614f143e53e49826c0955a36255',1,'WebAPI.Mapping.Models.Abstract.Out.NamedModel.Name'],['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_i_named_model.html#abbd329f08e5f99a85d7b444e51dc5bc2',1,'WebAPI.Mapping.Models.Abstract.INamedModel.Name'],['../class_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_base_update_named_model.html#a0e48f2342f5edeb3e4df3f74dfc8ee8f',1,'WebAPI.Mapping.Models.Abstract.In.BaseUpdateNamedModel.Name'],['../class_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_base_create_named_entity_model.html#a3ee76bfd3d8dafaf87ab0a050b967370',1,'WebAPI.Mapping.Models.Abstract.In.BaseCreateNamedEntityModel.Name'],['../class_domain_1_1_abstract_1_1_named_entity.html#ac89f14123b203e71d2d1e888ad594b92',1,'Domain.Abstract.NamedEntity.Name'],['../interface_domain_1_1_abstract_1_1_i_named_entity.html#a98c9383fbb6896e8c180dbd7994e5877',1,'Domain.Abstract.INamedEntity.Name'],['../class_domain_1_1_name.html',1,'Domain.Name']]],
  ['name_2ecs_1',['Name.cs',['../_name_8cs.html',1,'']]],
  ['namedentity_2',['namedentity',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain.Abstract.NamedEntity&lt; TEntity &gt;'],['../class_domain_1_1_abstract_1_1_named_entity.html#a4fe0947197c8cfbad01776b26a5b8e09',1,'Domain.Abstract.NamedEntity.NamedEntity()']]],
  ['namedentity_2ecs_3',['NamedEntity.cs',['../_named_entity_8cs.html',1,'']]],
  ['namedentity_3c_20booktype_20_3e_4',['NamedEntity&lt; BookType &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20cabinet_20_3e_5',['NamedEntity&lt; Cabinet &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20city_20_3e_6',['NamedEntity&lt; City &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20color_20_3e_7',['NamedEntity&lt; Color &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20genre_20_3e_8',['NamedEntity&lt; Genre &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20language_20_3e_9',['NamedEntity&lt; Language &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20room_20_3e_10',['NamedEntity&lt; Room &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20seria_20_3e_11',['NamedEntity&lt; Seria &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20shelf_20_3e_12',['NamedEntity&lt; Shelf &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentity_3c_20street_20_3e_13',['NamedEntity&lt; Street &gt;',['../class_domain_1_1_abstract_1_1_named_entity.html',1,'Domain::Abstract']]],
  ['namedentitycomparer_14',['NamedEntityComparer',['../class_domain_1_1_abstract_1_1_named_entity_comparer.html',1,'Domain::Abstract']]],
  ['namedentitycomparer_7btentity_7d_2ecs_15',['NamedEntityComparer{TEntity}.cs',['../_named_entity_comparer_02_t_entity_03_8cs.html',1,'']]],
  ['namedmodel_16',['NamedModel',['../class_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_out_1_1_named_model.html',1,'WebAPI::Mapping::Models::Abstract::Out']]],
  ['namedmodel_2ecs_17',['NamedModel.cs',['../_named_model_8cs.html',1,'']]],
  ['namedprofile_18',['namedprofile',['../class_web_a_p_i_1_1_mapping_1_1_profiles_1_1_abstract_1_1_named_profile.html#a7533268c374d0c184875199ac6a8df3f',1,'WebAPI.Mapping.Profiles.Abstract.NamedProfile.NamedProfile()'],['../class_web_a_p_i_1_1_mapping_1_1_profiles_1_1_abstract_1_1_named_profile.html',1,'WebAPI.Mapping.Profiles.Abstract.NamedProfile&lt; TEntity, TCreateModel, TUpdateModel, TOutModel &gt;']]],
  ['namedprofile_3c_20city_2c_20citycreatemodel_2c_20cityupdatemodel_2c_20cityoutmodel_20_3e_19',['NamedProfile&lt; City, CityCreateModel, CityUpdateModel, CityOutModel &gt;',['../class_web_a_p_i_1_1_mapping_1_1_profiles_1_1_abstract_1_1_named_profile.html',1,'WebAPI::Mapping::Profiles::Abstract']]],
  ['namedprofile_3c_20shelf_2c_20shelfcreatemodel_2c_20shelfupdatemodel_2c_20shelfoutmodel_20_3e_20',['NamedProfile&lt; Shelf, ShelfCreateModel, ShelfUpdateModel, ShelfOutModel &gt;',['../class_web_a_p_i_1_1_mapping_1_1_profiles_1_1_abstract_1_1_named_profile.html',1,'WebAPI::Mapping::Profiles::Abstract']]],
  ['namedprofile_3c_20street_2c_20streetcreatemodel_2c_20streetupdatemodel_2c_20streetoutmode_20_3e_21',['NamedProfile&lt; Street, StreetCreateModel, StreetUpdateModel, StreetOutMode &gt;',['../class_web_a_p_i_1_1_mapping_1_1_profiles_1_1_abstract_1_1_named_profile.html',1,'WebAPI::Mapping::Profiles::Abstract']]],
  ['namedprofile_7btentity_2ctcreatemodel_2ctupdatemodel_2ctoutmodel_7d_2ecs_22',['NamedProfile{TEntity,TCreateModel,TUpdateModel,TOutModel}.cs',['../_named_profile_02_t_entity_00_t_create_model_00_t_update_model_00_t_out_model_03_8cs.html',1,'']]],
  ['nametests_23',['NameTests',['../class_domain_1_1_tests_1_1_name_tests.html',1,'Domain::Tests']]],
  ['nametests_2ecs_24',['NameTests.cs',['../_name_tests_8cs.html',1,'']]],
  ['newentitiesmigration_25',['NewEntitiesMigration',['../class_data_access_layer_1_1_migrations_1_1_new_entities_migration.html',1,'DataAccessLayer::Migrations']]],
  ['newordermigration_26',['NewOrderMigration',['../class_data_access_layer_1_1_migrations_1_1_new_order_migration.html',1,'DataAccessLayer::Migrations']]],
  ['newversionmigration_27',['NewVersionMigration',['../class_data_access_layer_1_1_migrations_1_1_new_version_migration.html',1,'DataAccessLayer::Migrations']]],
  ['notequalsoperator_5fvaliddata_5fsuccess_28',['NotEqualsOperator_ValidData_Success',['../class_domain_1_1_tests_1_1_name_tests.html#acbbb00e12413bd44910bc672fa73670f',1,'Domain::Tests::NameTests']]]
];
