var searchData=
[
  ['iauthorrepository_0',['IAuthorRepository',['../interface_repository_1_1_abstract_1_1_i_author_repository.html',1,'Repository::Abstract']]],
  ['ibilingualnamedentity_1',['IBilingualNamedEntity',['../interface_domain_1_1_abstract_1_1_i_bilingual_named_entity.html',1,'Domain::Abstract']]],
  ['ibilingualnamedmodel_2',['IBilingualNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_i_bilingual_named_model.html',1,'WebAPI::Mapping::Models::Abstract']]],
  ['ibookrepository_3',['IBookRepository',['../interface_repository_1_1_abstract_1_1_i_book_repository.html',1,'Repository::Abstract']]],
  ['icreatebilingualnamedmodel_4',['ICreateBilingualNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_create_bilingual_named_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['icreatemodel_5',['ICreateModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_create_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['icreatenamedmodel_6',['ICreateNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_create_named_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['ientity_7',['IEntity',['../interface_domain_1_1_abstract_1_1_i_entity.html',1,'Domain::Abstract']]],
  ['ientitycomparer_8',['IEntityComparer',['../interface_domain_1_1_abstract_1_1_i_entity_comparer.html',1,'Domain::Abstract']]],
  ['ientitycomparer_3c_20tentity_20_3e_9',['IEntityComparer&lt; TEntity &gt;',['../interface_domain_1_1_abstract_1_1_i_entity_comparer.html',1,'Domain::Abstract']]],
  ['iidmodel_10',['IIdModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_i_id_model.html',1,'WebAPI::Mapping::Models::Abstract']]],
  ['iinbilingualnamedmodel_11',['IInBilingualNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_in_bilingual_named_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['iinmodel_12',['IInModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_in_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['iinnamedmodel_13',['IInNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_in_named_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['imanuscriptrepository_14',['IManuscriptRepository',['../interface_repository_1_1_abstract_1_1_i_manuscript_repository.html',1,'Repository::Abstract']]],
  ['imodel_15',['IModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_i_model.html',1,'WebAPI::Mapping::Models::Abstract']]],
  ['inamedentity_16',['INamedEntity',['../interface_domain_1_1_abstract_1_1_i_named_entity.html',1,'Domain::Abstract']]],
  ['inamedmodel_17',['INamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_i_named_model.html',1,'WebAPI::Mapping::Models::Abstract']]],
  ['initialmigration_18',['InitialMigration',['../class_data_access_layer_1_1_migrations_1_1_initial_migration.html',1,'DataAccessLayer::Migrations']]],
  ['ioutbilingualnamedmodel_19',['IOutBilingualNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_out_1_1_i_out_bilingual_named_model.html',1,'WebAPI::Mapping::Models::Abstract::Out']]],
  ['ioutmodel_20',['IOutModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_out_1_1_i_out_model.html',1,'WebAPI::Mapping::Models::Abstract::Out']]],
  ['ioutnamedmodel_21',['IOutNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_out_1_1_i_out_named_model.html',1,'WebAPI::Mapping::Models::Abstract::Out']]],
  ['iperson_22',['IPerson',['../interface_domain_1_1_abstract_1_1_i_person.html',1,'Domain::Abstract']]],
  ['iperson_3c_20t_20_3e_23',['IPerson&lt; T &gt;',['../interface_domain_1_1_abstract_1_1_i_person.html',1,'Domain::Abstract']]],
  ['irepository_24',['IRepository',['../interface_repository_1_1_abstract_1_1_i_repository.html',1,'Repository::Abstract']]],
  ['ishelfrepository_25',['IShelfRepository',['../interface_repository_1_1_abstract_1_1_i_shelf_repository.html',1,'Repository::Abstract']]],
  ['item_26',['Item',['../class_domain_1_1_item.html',1,'Domain']]],
  ['iupdatebilingualnamedmodel_27',['IUpdateBilingualNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_update_bilingual_named_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['iupdatemodel_28',['IUpdateModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_update_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]],
  ['iupdatenamedmodel_29',['IUpdateNamedModel',['../interface_web_a_p_i_1_1_mapping_1_1_models_1_1_abstract_1_1_in_1_1_i_update_named_model.html',1,'WebAPI::Mapping::Models::Abstract::In']]]
];
