// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorManuscript", b =>
                {
                    b.Property<Guid>("AuthorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManuscriptsId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorsId", "ManuscriptsId");

                    b.HasIndex("ManuscriptsId");

                    b.ToTable("AuthorManuscript", (string)null);
                });

            modelBuilder.Entity("BookManuscript", b =>
                {
                    b.Property<Guid>("BooksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManuscriptsId")
                        .HasColumnType("uuid");

                    b.HasKey("BooksId", "ManuscriptsId");

                    b.HasIndex("ManuscriptsId");

                    b.ToTable("BookManuscript", (string)null);
                });

            modelBuilder.Entity("BookPublisher", b =>
                {
                    b.Property<Guid>("BooksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublishersId")
                        .HasColumnType("uuid");

                    b.HasKey("BooksId", "PublishersId");

                    b.HasIndex("PublishersId");

                    b.ToTable("BookPublisher", (string)null);
                });

            modelBuilder.Entity("Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Apartment")
                        .HasColumnType("integer")
                        .HasComment("Номер квартиры");

                    b.Property<string>("BuildingSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Корпус или владение");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("House")
                        .HasColumnType("integer")
                        .HasComment("Номер дома");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Domain.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Annotation")
                        .HasColumnType("text")
                        .HasComment("Аннотация");

                    b.Property<Guid>("BookTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Doi")
                        .HasColumnType("text")
                        .HasComment("DOI");

                    b.Property<string>("Edition")
                        .HasColumnType("text");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ISBN")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasComment("ISBN");

                    b.Property<int>("Pages")
                        .HasColumnType("integer")
                        .HasComment("Количество страниц");

                    b.Property<Guid?>("SeriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Название книги");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("URL");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer")
                        .HasComment("Том");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookTypeId");

                    b.HasIndex("EditorId");

                    b.HasIndex("SeriaId");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Domain.BookType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BookTypes", (string)null);
                });

            modelBuilder.Entity("Domain.Cabinet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Cabinets", null, t =>
                        {
                            t.HasComment("Шкафы в комнатах");
                        });
                });

            modelBuilder.Entity("Domain.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Domain.Editor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Editors", (string)null);
                });

            modelBuilder.Entity("Domain.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShelfId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ShelfId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Domain.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Domain.Manuscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Manuscripts", null, t =>
                        {
                            t.HasComment("Рукописи произведений");
                        });
                });

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateBirth")
                        .HasColumnType("date")
                        .HasComment("Дата рождения");

                    b.Property<DateOnly?>("DateDeath")
                        .HasColumnType("date")
                        .HasComment("Дата смерти");

                    b.HasKey("Id");

                    b.ToTable("Persons", null, t =>
                        {
                            t.HasComment("Персоны: авторы, переводчики, редакторы");
                        });
                });

            modelBuilder.Entity("Domain.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("Domain.Reviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Reviwers", (string)null);
                });

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Rooms", null, t =>
                        {
                            t.HasComment("Комнаты");
                        });
                });

            modelBuilder.Entity("Domain.Seria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Serias", (string)null);
                });

            modelBuilder.Entity("Domain.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CabinetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Название полки");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.ToTable("Shelves", (string)null);
                });

            modelBuilder.Entity("Domain.Street", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Streets", (string)null);
                });

            modelBuilder.Entity("Domain.Translator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Translators", (string)null);
                });

            modelBuilder.Entity("GenreManuscript", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManuscriptsId")
                        .HasColumnType("uuid");

                    b.HasKey("GenresId", "ManuscriptsId");

                    b.HasIndex("ManuscriptsId");

                    b.ToTable("GenreManuscript", (string)null);
                });

            modelBuilder.Entity("LanguageManuscript", b =>
                {
                    b.Property<Guid>("LanguagesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManuscriptsId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguagesId", "ManuscriptsId");

                    b.HasIndex("ManuscriptsId");

                    b.ToTable("LanguageManuscript", (string)null);
                });

            modelBuilder.Entity("ManuscriptReviewer", b =>
                {
                    b.Property<Guid>("ManuscriptsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewersId")
                        .HasColumnType("uuid");

                    b.HasKey("ManuscriptsId", "ReviewersId");

                    b.HasIndex("ReviewersId");

                    b.ToTable("ManuscriptReviewer", (string)null);
                });

            modelBuilder.Entity("ManuscriptTranslator", b =>
                {
                    b.Property<Guid>("ManuscriptsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TranslatorsId")
                        .HasColumnType("uuid");

                    b.HasKey("ManuscriptsId", "TranslatorsId");

                    b.HasIndex("TranslatorsId");

                    b.ToTable("ManuscriptTranslator", (string)null);
                });

            modelBuilder.Entity("AuthorManuscript", b =>
                {
                    b.HasOne("Domain.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manuscript", null)
                        .WithMany()
                        .HasForeignKey("ManuscriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookManuscript", b =>
                {
                    b.HasOne("Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manuscript", null)
                        .WithMany()
                        .HasForeignKey("ManuscriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookPublisher", b =>
                {
                    b.HasOne("Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Publisher", null)
                        .WithMany()
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Address", b =>
                {
                    b.HasOne("Domain.Street", "Street")
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("Domain.Author", b =>
                {
                    b.HasOne("Domain.Person", "Person")
                        .WithOne("Author")
                        .HasForeignKey("Domain.Author", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Book", b =>
                {
                    b.HasOne("Domain.BookType", "BookType")
                        .WithMany("Books")
                        .HasForeignKey("BookTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Domain.Editor", "Editor")
                        .WithMany("Books")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Seria", "Seria")
                        .WithMany("Books")
                        .HasForeignKey("SeriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookType");

                    b.Navigation("Editor");

                    b.Navigation("Seria");
                });

            modelBuilder.Entity("Domain.BookType", b =>
                {
                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("BookTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("BookTypeName")
                                .HasComment("Тип книги");

                            b1.HasKey("BookTypeId");

                            b1.ToTable("BookTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Cabinet", b =>
                {
                    b.HasOne("Domain.Room", "Room")
                        .WithMany("Cabinets")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("CabinetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CabinetName")
                                .HasComment("Название шкафа");

                            b1.HasKey("CabinetId");

                            b1.ToTable("Cabinets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CabinetId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.City", b =>
                {
                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CityName")
                                .HasComment("Название города");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Editor", b =>
                {
                    b.HasOne("Domain.Person", "Person")
                        .WithOne("Editor")
                        .HasForeignKey("Domain.Editor", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Genre", b =>
                {
                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("GenreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("GenreName")
                                .HasComment("Жанр");

                            b1.HasKey("GenreId");

                            b1.ToTable("Genres", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GenreId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.HasOne("Domain.Book", "Book")
                        .WithMany("Items")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Domain.Shelf", "Shelf")
                        .WithMany("Items")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Book");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Domain.Language", b =>
                {
                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("LanguageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LanguageName")
                                .HasComment("Язык");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Manuscript", b =>
                {
                    b.OwnsOne("Staff.Range<System.DateOnly>", "Dates", b1 =>
                        {
                            b1.Property<Guid>("ManuscriptId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("DateFrom")
                                .HasComment("Дата начала написания");

                            b1.Property<DateOnly>("To")
                                .HasColumnType("date")
                                .HasColumnName("DateTo")
                                .HasComment("Дата окончания написания");

                            b1.HasKey("ManuscriptId");

                            b1.ToTable("Manuscripts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ManuscriptId");
                        });

                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("ManuscriptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ManuscriptTitle")
                                .HasComment("Название произведения");

                            b1.HasKey("ManuscriptId");

                            b1.ToTable("Manuscripts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ManuscriptId");
                        });

                    b.OwnsOne("Domain.Title", "OriginName", b1 =>
                        {
                            b1.Property<Guid>("ManuscriptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ManuscriptOriginTitle")
                                .HasComment("Оригинальное название произведения");

                            b1.HasKey("ManuscriptId");

                            b1.ToTable("Manuscripts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ManuscriptId");
                        });

                    b.Navigation("Dates");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OriginName");
                });

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.OwnsOne("Domain.Name", "FullName", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FamilyName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FamilyName")
                                .HasComment("Фамилия персоны");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName")
                                .HasComment("Имя персоны");

                            b1.Property<string>("PatronymicName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PatronymicName")
                                .HasComment("Отчество персоны");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Publisher", b =>
                {
                    b.HasOne("Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("PublisherId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("PublisherName")
                                .HasComment("Название издательства");

                            b1.HasKey("PublisherId");

                            b1.ToTable("Publishers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PublisherId");
                        });

                    b.OwnsOne("Domain.Title", "OriginName", b1 =>
                        {
                            b1.Property<Guid>("PublisherId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("PublisheOriginName")
                                .HasComment("Оригинальное название издательства");

                            b1.HasKey("PublisherId");

                            b1.ToTable("Publishers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PublisherId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OriginName");
                });

            modelBuilder.Entity("Domain.Reviewer", b =>
                {
                    b.HasOne("Domain.Person", "Person")
                        .WithOne("Reviewer")
                        .HasForeignKey("Domain.Reviewer", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.HasOne("Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("RoomName")
                                .HasComment("Название комнаты");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Seria", b =>
                {
                    b.OwnsOne("Domain.Title", "SeriaName", b1 =>
                        {
                            b1.Property<Guid>("SeriaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("SeriaName")
                                .HasComment("Серия");

                            b1.HasKey("SeriaId");

                            b1.ToTable("Serias", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SeriaId");
                        });

                    b.Navigation("SeriaName")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Shelf", b =>
                {
                    b.HasOne("Domain.Cabinet", "Cabinet")
                        .WithMany("Shelves")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Domain.Street", b =>
                {
                    b.HasOne("Domain.City", "City")
                        .WithMany("Streets")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Title", "Name", b1 =>
                        {
                            b1.Property<Guid>("StreetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("StreetName")
                                .HasComment("Название улицы");

                            b1.HasKey("StreetId");

                            b1.ToTable("Streets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StreetId");
                        });

                    b.Navigation("City");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Translator", b =>
                {
                    b.HasOne("Domain.Person", "Person")
                        .WithOne("Translator")
                        .HasForeignKey("Domain.Translator", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GenreManuscript", b =>
                {
                    b.HasOne("Domain.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manuscript", null)
                        .WithMany()
                        .HasForeignKey("ManuscriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageManuscript", b =>
                {
                    b.HasOne("Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manuscript", null)
                        .WithMany()
                        .HasForeignKey("ManuscriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManuscriptReviewer", b =>
                {
                    b.HasOne("Domain.Manuscript", null)
                        .WithMany()
                        .HasForeignKey("ManuscriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Reviewer", null)
                        .WithMany()
                        .HasForeignKey("ReviewersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManuscriptTranslator", b =>
                {
                    b.HasOne("Domain.Manuscript", null)
                        .WithMany()
                        .HasForeignKey("ManuscriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Translator", null)
                        .WithMany()
                        .HasForeignKey("TranslatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Book", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.BookType", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Cabinet", b =>
                {
                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("Domain.City", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Domain.Editor", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.Navigation("Author");

                    b.Navigation("Editor");

                    b.Navigation("Reviewer");

                    b.Navigation("Translator");
                });

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.Navigation("Cabinets");
                });

            modelBuilder.Entity("Domain.Seria", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Shelf", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
